bintomon: bintomon.c
	gcc -Wall -O2 -o bintomon bintomon.c

# ------------------------------------------------------------------------------
# Uncomment to install to your linux system, else use full path in
# your scripts.
#install: bintomon
#	cp bintomon /usr/local/bin/bintomon 
# ------------------------------------------------------------------------------

clean:
	$(RM) bintomon

distclean: clean
